"""Briefs are generated by task code, so they are generated where task code is confined."""

import os
import shutil
import subprocess
import sys

import pytest

from drillion import catalogue, manifest, sandbox
from drillion.settings import settings
from tests.fixtures import tasks_root
from tests.fixtures_manifest import fixture_task

SLUG = "271_fixture"


def _grader(body, head=""):
    """Replace the fixture task's grade.py with one whose `brief` is `body`, under `head`."""
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        f"{head}\n\n\ndef brief(r):\n    {body}\n\n\ndef check(doc, b):\n    pass\n",
        encoding="utf-8",
    )


@pytest.fixture
def fixture_root():
    tmp = tasks_root(**{SLUG: fixture_task()})
    keep = settings.root
    settings.root = tmp
    yield tmp
    settings.root = keep
    shutil.rmtree(tmp, ignore_errors=True)


def test_a_brief_is_generated_and_is_deterministic(fixture_root):
    meta = catalogue.tasks()[SLUG]
    first = manifest.generate_brief(meta, 4242)
    assert first == manifest.generate_brief(meta, 4242)
    assert first["name"] in ("checkout", "billing") and 2 <= first["replicas"] <= 5


def test_different_seeds_can_give_different_briefs(fixture_root):
    meta = catalogue.tasks()[SLUG]
    seen = {
        tuple(sorted(manifest.generate_brief(meta, s).items()))
        for s in range(1000, 1040)
    }
    assert len(seen) > 1, "the brief must actually vary with the seed"


def test_the_server_never_imports_the_grader(fixture_root):
    """A grader loaded in this process would leave its module-level writes in this process."""
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        'import os\n\nos.environ["DRILLION_GRADER_RAN_IN_THE_SERVER"] = "1"\n\n\n'
        "def brief(r):\n    return {'n': 1}\n",
        encoding="utf-8",
    )
    meta = catalogue.tasks()[SLUG]
    manifest.generate_brief(meta, 7)
    assert "DRILLION_GRADER_RAN_IN_THE_SERVER" not in os.environ
    assert not any(SLUG in name or name == "grade" for name in sys.modules)


@pytest.mark.parametrize(
    "returns",
    [
        "object()",
        "[1, 2]",
        "{'a': {'b': 1}}",
        "{'a b': 1}",
        "{'n': float('inf')}",
        "{'n': float('nan')}",
    ],
)
def test_a_brief_that_is_not_a_flat_mapping_of_finite_scalars_is_rejected(
    fixture_root, returns
):
    _grader(f"return {returns}")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_brief_may_hold_a_bool(fixture_root):
    _grader("return {'ready': True}")
    assert manifest.generate_brief(catalogue.tasks()[SLUG], 7) == {"ready": True}


def test_a_grader_that_explodes_is_rejected_not_crashed(fixture_root):
    _grader("raise ValueError('boom')")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_the_guard_tier_still_has_its_audit_hook(fixture_root, tmp_path, monkeypatch):
    """With no kernel tier the audit hook is the only thing between a grader and the rest of
    the disk, and it is in the child only because the brief script imports it first."""
    monkeypatch.setattr(sandbox, "_landlock_works", lambda: False)
    monkeypatch.setattr(sandbox, "status", lambda: ("guard", "forced by a test"))
    escaped = tmp_path / "escaped.txt"
    _grader(f"open({str(escaped)!r}, 'w').write('out')")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)
    assert not escaped.exists(), "the grader wrote outside its scratch directory"


def test_a_grader_that_never_finishes_is_rejected_not_crashed(
    fixture_root, monkeypatch
):
    """A runaway brief() must reach the caller as a rejection, never as a traceback."""

    def slow(*a, **k):
        raise subprocess.TimeoutExpired(["python"], manifest.BRIEF_SECONDS)

    monkeypatch.setattr(manifest.sandbox, "run_script", slow)
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_cannot_point_the_server_at_a_file_it_cannot_read(
    fixture_root, tmp_path
):
    """The child owns the scratch directory, so it can leave a symlink where its output goes.
    The parent must not follow it: that would read, on the grader's behalf, a file the
    sandbox denies the grader."""
    secret = tmp_path / "secret.json"
    secret.write_text('{"aws_key": "AKIAEXFILTRATED"}', encoding="utf-8")
    _grader(
        f"os.symlink({str(secret)!r}, sys.argv[3]); os._exit(0)", head="import os, sys"
    )
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_cannot_wedge_the_server_on_a_fifo(fixture_root):
    """Opening a fifo for reading blocks until someone writes. The parent must not block."""
    _grader("os.mkfifo(sys.argv[3]); os._exit(0)", head="import os, sys")
    with pytest.raises(manifest.Rejected, match="not a plain file"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_brief_over_the_size_cap_is_rejected(fixture_root):
    _grader(f"return {{'pad': 'x' * {manifest.MAX_BRIEF_BYTES}}}")
    with pytest.raises(manifest.Rejected, match="too much"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_that_exits_clean_without_writing_is_rejected(fixture_root):
    _grader("os._exit(0)", head="import os")
    with pytest.raises(manifest.Rejected, match="wrote nothing"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_that_writes_a_good_brief_then_fails_is_rejected(fixture_root):
    """A non-zero exit is a rejection even when the output file is perfectly valid, and the
    grader's own stderr is what tells the author why."""
    _grader(
        "open(sys.argv[3], 'w').write(json.dumps({'name': 'c', 'replicas': 2}));"
        " raise SystemExit('the grader gave up')",
        head="import json, sys",
    )
    with pytest.raises(manifest.Rejected, match="the grader gave up"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_render_fills_placeholders_and_survives_doubled_braces():
    assert manifest.render("a {name} b", {"name": "x"}) == "a x b"
    assert manifest.render("a {{literal}} b", {}) == "a {literal} b"


@pytest.mark.parametrize(
    "template",
    ["{missing}", "{name.nope}", "{replicas[0]}", "{name:d}", "{0}", "{name"],
)
def test_a_template_the_brief_does_not_fit_is_rejected(template):
    """Every placeholder mistake a task author can make is a `Rejected`, never a traceback
    out of the server."""
    with pytest.raises(manifest.Rejected):
        manifest.render(template, {"name": "checkout", "replicas": 2})


def test_a_template_cannot_allocate_without_bound():
    with pytest.raises(manifest.Rejected, match="too long"):
        wide = "{name:>" + str(manifest.MAX_SPEC_CHARS + 1) + "}"
        manifest.render(wide, {"name": "x"})
