"""Briefs are generated by task code, so they are generated where task code is confined."""

import asyncio
import os
import shutil
import subprocess
import sys
from types import SimpleNamespace

import httpx
import pytest
import yaml

from drillion import attempts, catalogue, kinds, manifest, runner, sandbox, state, tools
from drillion.api import app
from drillion.settings import settings
from tests.fixtures import tasks_root
from tests.fixtures_manifest import fixture_task, stub_kubeconform

SLUG = "271_fixture"
CORRECT = (
    "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: checkout\n"
    "spec:\n  replicas: 3\n"
)
BRIEF = {"name": "checkout", "replicas": 3}


def _grader(body, head=""):
    """Replace the fixture task's grade.py with one whose `brief` is `body`, under `head`."""
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        f"{head}\n\n\ndef brief(r):\n    {body}\n\n\ndef check(doc, b):\n    pass\n",
        encoding="utf-8",
    )


@pytest.fixture
def fixture_root():
    tmp = tasks_root(**{SLUG: fixture_task()})
    keep = settings.root
    settings.root = tmp
    yield tmp
    settings.root = keep
    shutil.rmtree(tmp, ignore_errors=True)


@pytest.fixture
def installed_kubeconform():
    """The real grader, once the release gate has filled the pins."""
    if tools.installed(tools.KUBECONFORM) is None:
        pytest.skip("kubeconform is not installed: run `drillion doctor --fetch`")


@pytest.fixture
def stubbed_kubeconform(fixture_root, monkeypatch):
    """The stand-in, so the grading path is exercised before the pins land rather than
    skipped until then. `installed_kubeconform` is the same tests against the real tool."""
    if os.name == "nt":
        pytest.skip("the stand-in is a shebang script, so it needs a posix exec")
    # written once, so a test that moves a grading input moves what the grader passes
    # rather than what the stand-in expects
    path = stub_kubeconform(fixture_root)
    monkeypatch.setattr(tools, "installed", lambda name: path)


def _submit(text):
    """(passed, the first diagnostic as `path: message`): the grader's own words, as data.

    The diagnostics are what the page is given, so the tests assert on the field and the
    sentence rather than on whatever a test framework printed around them."""
    (settings.tasks_dir / SLUG / "task.yaml").write_text(text, encoding="utf-8")
    passed, diagnostics, _ = runner.run_manifest(catalogue.tasks()[SLUG], BRIEF)
    if not diagnostics:
        return passed, ""
    first = diagnostics[0]
    said = first["message"]
    return passed, f"{first['path']}: {said}" if first["path"] else said


def test_a_correct_manifest_passes(stubbed_kubeconform):
    passed, headline = _submit(CORRECT)
    assert passed, headline


def test_a_correct_manifest_passes_the_real_validator(
    fixture_root, installed_kubeconform
):
    """The same submission against the pinned tool rather than the stand-in. Skipped until
    the release gate fills the pins, and then it is what says the stand-in told the truth."""
    passed, headline = _submit(CORRECT)
    assert passed, headline


def test_a_manifest_that_misses_the_brief_says_which_requirement(stubbed_kubeconform):
    passed, headline = _submit(CORRECT.replace("replicas: 3", "replicas: 9"))
    assert not passed and "replicas" in headline


@pytest.mark.parametrize(
    "submission, says",
    [
        ("", "empty"),
        ("  \n\n", "empty"),
        ("kind: Deployment\n---\nkind: Service\n", "one document"),
        ("- kind: Deployment\n", "must be a mapping"),
    ],
)
def test_a_submission_that_is_not_one_document_is_rejected(
    stubbed_kubeconform, submission, says
):
    """These are refused before the schema: kubeconform has nothing useful to say about a
    file the learner has not written yet."""
    passed, headline = _submit(submission)
    assert not passed and says in headline.lower()


def test_what_the_schema_rejects_reaches_the_learner(stubbed_kubeconform):
    """The field that is wrong, not kubeconform's boilerplate: `msg` says only "problem
    validating schema" and carries the absolute path drillion installed the schema at."""
    passed, headline = _submit(CORRECT.replace("replicas: 3", 'replicas: "3"'))
    assert not passed
    assert "/spec/replicas: expected integer, but got string" in headline, headline
    assert "problem validating schema" not in headline, (
        "boilerplate reached the learner"
    )


def test_a_rejection_with_no_field_detail_still_says_what_the_validator_said(
    stubbed_kubeconform,
):
    """Not every rejection is a field comparison, and then `msg` is all there is."""
    passed, headline = _submit(CORRECT.replace("apiVersion: apps/v1\n", ""))
    assert not passed and "error while parsing: missing 'apiVersion' key" in headline


def test_a_kind_no_schema_is_packaged_for_is_not_blamed_on_the_learner(
    stubbed_kubeconform,
):
    """kubeconform says "could not find schema" both for a typo in `kind:` and for a kind
    drillion never packaged. It cannot tell them apart from here, so it says so rather than
    telling a learner with a correct manifest that they are wrong."""
    passed, headline = _submit(CORRECT.replace("kind: Deployment", "kind: ConfigMap"))
    assert not passed
    assert "could not find schema for ConfigMap" in headline
    assert "not your mistake" in headline, headline


def test_a_validator_that_cannot_run_is_not_silently_a_wrong_answer(
    stubbed_kubeconform, monkeypatch
):
    """An invocation the validator refuses prints no JSON report. What it did say is what
    the learner is shown, or a grader that never ran reads as their mistake."""
    monkeypatch.setattr(tools, "KUBERNETES_VERSION", "9.9.9")
    passed, headline = _submit(CORRECT)
    assert not passed and "unexpected invocation" in headline


def test_a_missing_tool_is_not_a_wrong_answer(fixture_root, monkeypatch):
    monkeypatch.setattr(tools, "installed", lambda name: None)
    with pytest.raises(manifest.ToolMissing):
        manifest.job(catalogue.tasks()[SLUG], BRIEF)


def test_a_missing_tool_reaches_the_learner_as_infrastructure(
    fixture_root, monkeypatch
):
    """A 503 naming the fix, never a failing test: nothing about their answer is known."""
    monkeypatch.setattr(tools, "installed", lambda name: None)

    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            opened = (await api.post(f"/api/task/{SLUG}/open")).json()
            reply = await api.post(
                f"/api/task/{SLUG}/run",
                json={"code": CORRECT, "etag": opened["etag"], "submit": True},
            )
            assert reply.status_code == 503, reply.text
            assert "doctor --fetch" in reply.json()["error"]

    asyncio.run(drive())


def test_a_sitting_with_no_brief_is_refused_rather_than_graded(fixture_root):
    """An attempt opened before manifest grading existed has no stored requirements, and
    the spec it was given still holds raw placeholders. There is nothing to grade against,
    so it is refused with the way out rather than graded against a brief nobody read."""
    meta = catalogue.tasks()[SLUG]
    with pytest.raises(manifest.Rejected, match="abandon"):
        kinds.of(meta).grade(meta, {"seed": 7}, "")


@pytest.mark.parametrize("term", ["grader", "version", "pin", "schemas"])
def test_the_fingerprint_changes_when_any_grading_input_changes(
    fixture_root, monkeypatch, term
):
    """What decided the verdict, not what the learner wrote: every input is in the digest."""
    meta = catalogue.tasks()[SLUG]
    before = manifest.fingerprint(meta)
    assert before.startswith("m1:") and before == manifest.fingerprint(meta)
    if term == "grader":
        _grader("return {'name': 'checkout'}")
    elif term == "version":
        monkeypatch.setattr(tools, "KUBERNETES_VERSION", "9.9.9")
    elif term == "pin":
        moved = tools.pin_for(tools.KUBECONFORM)._replace(
            version="9.9.9", binary_sha256="ff"
        )
        monkeypatch.setattr(tools, "pin_for", lambda name: moved)
    else:
        monkeypatch.setattr(tools, "schema_digest", lambda: "a different set")
    assert manifest.fingerprint(meta) != before


def test_a_brief_is_generated_and_is_deterministic(fixture_root):
    meta = catalogue.tasks()[SLUG]
    first = manifest.generate_brief(meta, 4242)
    assert first == manifest.generate_brief(meta, 4242)
    assert first["name"] in ("checkout", "billing") and 2 <= first["replicas"] <= 5


def test_different_seeds_can_give_different_briefs(fixture_root):
    meta = catalogue.tasks()[SLUG]
    seen = {
        tuple(sorted(manifest.generate_brief(meta, s).items()))
        for s in range(1000, 1040)
    }
    assert len(seen) > 1, "the brief must actually vary with the seed"


def test_the_server_never_imports_the_grader(fixture_root):
    """A grader loaded in this process would leave its module-level writes in this process."""
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        'import os\n\nos.environ["DRILLION_GRADER_RAN_IN_THE_SERVER"] = "1"\n\n\n'
        "def brief(r):\n    return {'n': 1}\n",
        encoding="utf-8",
    )
    meta = catalogue.tasks()[SLUG]
    manifest.generate_brief(meta, 7)
    assert "DRILLION_GRADER_RAN_IN_THE_SERVER" not in os.environ
    assert not any(SLUG in name or name == "grade" for name in sys.modules)


@pytest.mark.parametrize(
    "returns",
    [
        "object()",
        "[1, 2]",
        "{'a': {'b': 1}}",
        "{'a b': 1}",
        "{'n': float('inf')}",
        "{'n': float('nan')}",
    ],
)
def test_a_brief_that_is_not_a_flat_mapping_of_finite_scalars_is_rejected(
    fixture_root, returns
):
    _grader(f"return {returns}")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_brief_may_hold_a_bool(fixture_root):
    _grader("return {'ready': True}")
    assert manifest.generate_brief(catalogue.tasks()[SLUG], 7) == {"ready": True}


def test_a_brief_can_be_read_when_posix_open_flags_are_unavailable(
    fixture_root, monkeypatch
):
    """Windows has neither flag; a normal brief must still open there."""
    _grader("return {'name': 'checkout', 'replicas': 3}")
    windows_os = SimpleNamespace(
        open=os.open,
        lstat=os.lstat,
        fstat=os.fstat,
        path=os.path,
        O_RDONLY=os.O_RDONLY,
    )
    monkeypatch.setattr(manifest, "os", windows_os)

    assert manifest.generate_brief(catalogue.tasks()[SLUG], 7) == BRIEF


def test_a_grader_that_explodes_is_rejected_not_crashed(fixture_root):
    _grader("raise ValueError('boom')")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_the_guard_tier_still_has_its_audit_hook(fixture_root, tmp_path, monkeypatch):
    """With no kernel tier the audit hook is the only thing between a grader and the rest of
    the disk, and it is in the child only because the brief script imports it first."""
    monkeypatch.setattr(sandbox, "_landlock_works", lambda: False)
    monkeypatch.setattr(sandbox, "status", lambda: ("guard", "forced by a test"))
    escaped = tmp_path / "escaped.txt"
    _grader(f"open({str(escaped)!r}, 'w').write('out')")
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)
    assert not escaped.exists(), "the grader wrote outside its scratch directory"


def test_a_grader_that_never_finishes_is_rejected_not_crashed(
    fixture_root, monkeypatch
):
    """A runaway brief() must reach the caller as a rejection, never as a traceback."""

    def slow(*a, **k):
        raise subprocess.TimeoutExpired(["python"], manifest.BRIEF_SECONDS)

    monkeypatch.setattr(manifest.sandbox, "run_script", slow)
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_cannot_point_the_server_at_a_file_it_cannot_read(
    fixture_root, tmp_path
):
    """The child owns the scratch directory, so it can leave a symlink where its output goes.
    The parent must not follow it: that would read, on the grader's behalf, a file the
    sandbox denies the grader."""
    secret = tmp_path / "secret.json"
    secret.write_text('{"aws_key": "AKIAEXFILTRATED"}', encoding="utf-8")
    _grader(
        f"os.symlink({str(secret)!r}, sys.argv[3]); os._exit(0)", head="import os, sys"
    )
    with pytest.raises(manifest.Rejected):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


@pytest.mark.skipif(not hasattr(os, "mkfifo"), reason="Windows has no FIFO API")
def test_a_grader_cannot_wedge_the_server_on_a_fifo(fixture_root):
    """Opening a fifo for reading blocks until someone writes. The parent must not block."""
    _grader("os.mkfifo(sys.argv[3]); os._exit(0)", head="import os, sys")
    with pytest.raises(manifest.Rejected, match="not a plain file"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_brief_over_the_size_cap_is_rejected(fixture_root):
    _grader(f"return {{'pad': 'x' * {manifest.MAX_BRIEF_BYTES}}}")
    with pytest.raises(manifest.Rejected, match="too much"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_that_exits_clean_without_writing_is_rejected(fixture_root):
    _grader("os._exit(0)", head="import os")
    with pytest.raises(manifest.Rejected, match="wrote nothing"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_a_grader_that_writes_a_good_brief_then_fails_is_rejected(fixture_root):
    """A non-zero exit is a rejection even when the output file is perfectly valid, and the
    grader's own stderr is what tells the author why."""
    _grader(
        "open(sys.argv[3], 'w').write(json.dumps({'name': 'c', 'replicas': 2}));"
        " raise SystemExit('the grader gave up')",
        head="import json, sys",
    )
    with pytest.raises(manifest.Rejected, match="the grader gave up"):
        manifest.generate_brief(catalogue.tasks()[SLUG], 7)


def test_render_fills_placeholders_and_survives_doubled_braces():
    assert manifest.render("a {name} b", {"name": "x"}) == "a x b"
    assert manifest.render("a {{literal}} b", {}) == "a {literal} b"


@pytest.mark.parametrize(
    "template",
    [
        "{missing}",
        "{name.nope}",
        "{replicas[0]}",
        "{name:d}",
        "{0}",
        "{name",
        "{}",
        "{name!r}",
        "{name:>1}",
        "{name:{name}}",
    ],
)
def test_a_template_the_brief_does_not_fit_is_rejected(template):
    """Every placeholder mistake a task author can make is a `Rejected`, never a traceback
    out of the server."""
    with pytest.raises(manifest.Rejected):
        manifest.render(template, {"name": "checkout", "replicas": 2})


def test_a_template_cannot_allocate_before_it_is_refused():
    """The width is refused on sight, so `format` never allocates a terabyte for it."""
    with pytest.raises(manifest.Rejected, match="plain name"):
        manifest.render("{name:>1000000000000}", {"name": "x"})


def test_a_filled_spec_is_still_bounded():
    with pytest.raises(manifest.Rejected, match="too long"):
        manifest.render("{name}", {"name": "x" * (manifest.MAX_SPEC_CHARS + 1)})


def test_the_grader_revision_moves_when_either_file_behind_a_brief_does(fixture_root):
    """Which generator produced a stored brief: both files it takes to make one count."""
    meta = catalogue.tasks()[SLUG]
    first = manifest.grader_revision(meta)
    assert first == manifest.grader_revision(meta) and len(first) == 12
    _grader("return {'name': 'checkout'}")
    second = manifest.grader_revision(meta)
    assert second != first, "a new grade.py is a new generator"
    (settings.tasks_dir / SLUG / "solution.yaml").write_text(
        "kind: Deployment\n", encoding="utf-8"
    )
    assert manifest.grader_revision(meta) not in (first, second), (
        "a new solution.yaml is a new generator too"
    )


def test_opening_persists_the_brief_and_the_rendered_spec(fixture_root):
    meta = catalogue.tasks()[SLUG]
    with state.writing() as st:
        o = attempts.open_attempt(st, SLUG, meta)
    assert o["brief"]["name"] in ("checkout", "billing")
    assert f"named `{o['brief']['name']}`" in o["spec_md"]
    assert "{name}" not in o["spec_md"]
    assert o["brief_revision"] == manifest.grader_revision(meta)


def test_an_edited_readme_does_not_change_an_open_sitting(fixture_root):
    with state.writing() as st:
        first = attempts.open_attempt(st, SLUG, catalogue.tasks()[SLUG])["spec_md"]
    readme = settings.tasks_dir / SLUG / "README.md"
    readme.write_text(
        readme.read_text(encoding="utf-8").replace("Because", "CHANGED"),
        encoding="utf-8",
    )
    meta = catalogue.tasks()[SLUG]
    assert "CHANGED" in meta["spec_md"], "the catalogue never re-read the README"
    with state.writing() as st:
        again = attempts.open_attempt(st, SLUG, meta)
    assert again["spec_md"] == first
    # the serve path as well as the store: `api._payload` asks the kind, not the README
    assert kinds.of(meta).spec(meta, again) == first
    # nothing open: the README as written, placeholders and all
    assert kinds.of(meta).spec(meta, None) == meta["spec_md"]


def test_a_python_attempt_gains_no_manifest_fields(fixture_root):
    meta = {"kind": "python", "dir": settings.tasks_dir / SLUG, "hints": []}
    with state.writing() as st:
        o = attempts.open_attempt(st, "009_like", meta)
    assert not {"brief", "spec_md", "brief_revision"} & set(o)


def test_the_task_page_is_served_the_sitting_spec_not_the_readme(fixture_root):
    """The serve path end to end: `api._payload` asks the kind which guidance to show."""

    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            closed = (await api.get(f"/api/task/{SLUG}")).json()["spec_md"]
            assert "{name}" in closed, "nothing open, so the README as written"
            opened = (await api.post(f"/api/task/{SLUG}/open")).json()["spec_md"]
            assert "{name}" not in opened
            assert (await api.get(f"/api/task/{SLUG}")).json()["spec_md"] == opened

    asyncio.run(drive())


def test_a_manifest_run_is_graded_by_its_own_kind(fixture_root, monkeypatch):
    """`api.run_task` already holds a kind. Grading through anything else grades a
    learner's YAML as if it were Python, and reports "no tests ran" as a wrong answer."""
    seen = []

    def spy(self, meta, o, src):
        seen.append(o["brief"])
        return True, {
            "headline": [],
            "output": "",
            "printed": "",
            "case": None,
            "diagnostics": [],
        }

    monkeypatch.setattr(kinds._Manifest, "grade", spy, raising=False)

    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            opened = (await api.post(f"/api/task/{SLUG}/open")).json()
            reply = await api.post(
                f"/api/task/{SLUG}/run",
                json={
                    "code": "kind: Deployment\n",
                    "etag": opened["etag"],
                    "submit": False,
                },
            )
            assert reply.status_code == 200, reply.text
            assert reply.json()["passed"] is True

    asyncio.run(drive())
    assert seen and seen[0]["name"] in ("checkout", "billing")


def test_grader_revision_is_not_a_raw_concatenation(fixture_root):
    """Two files that concatenate to the same bytes must not share a revision: a digest
    per file is what keeps a change in one from being cancelled by a change in the other."""
    folder = settings.tasks_dir / SLUG
    revisions = set()
    for grade, solution in ((b"ab", b"c"), (b"a", b"bc")):
        (folder / "grade.py").write_bytes(grade)
        (folder / "solution.yaml").write_bytes(solution)
        revisions.add(manifest.grader_revision({"dir": folder}))
    assert len(revisions) == 2, "the two files were concatenated, not hashed apart"


def meta_for():
    return catalogue.tasks()[SLUG]


def test_a_solution_placeholder_keeps_its_type(fixture_root):
    doc = yaml.safe_load(
        manifest.render_solution(meta_for(), {"name": "checkout", "replicas": 3})
    )
    assert doc["spec"]["replicas"] == 3 and doc["metadata"]["name"] == "checkout"


def test_a_yaml_looking_string_stays_a_string(fixture_root):
    """`y`, `no` and `1.0` are all YAML traps. A name is a name."""
    for value in ("y", "no", "1.0", "on"):
        doc = yaml.safe_load(
            manifest.render_solution(meta_for(), {"name": value, "replicas": 2})
        )
        assert doc["metadata"]["name"] == value, value


def test_a_value_with_a_colon_does_not_break_the_document(fixture_root):
    doc = yaml.safe_load(
        manifest.render_solution(meta_for(), {"name": "a: b", "replicas": 2})
    )
    assert doc["metadata"]["name"] == "a: b"


def test_a_placeholder_that_is_not_a_whole_scalar_is_rejected(fixture_root):
    solution = settings.tasks_dir / SLUG / "solution.yaml"
    solution.write_text("metadata:\n  name: prefix-{name}\n", encoding="utf-8")
    with pytest.raises(manifest.Rejected):
        manifest.render_solution(meta_for(), {"name": "checkout"})


def test_a_solution_missing_a_brief_value_is_rejected(fixture_root):
    with pytest.raises(
        manifest.Rejected, match="line 6: no brief value for 'replicas'"
    ):
        manifest.render_solution(meta_for(), {"name": "checkout"})


def test_a_solution_with_invalid_yaml_is_rejected(fixture_root):
    (settings.tasks_dir / SLUG / "solution.yaml").write_text(
        "metadata: [\n", encoding="utf-8"
    )
    with pytest.raises(manifest.Rejected, match="rendered solution is not valid YAML"):
        manifest.render_solution(meta_for(), BRIEF)


def test_the_manifest_solution_reveal_uses_the_stored_brief(fixture_root):
    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            opened = await api.post(f"/api/task/{SLUG}/open")
            assert opened.status_code == 200, opened.text
            assert opened.json()["reference"] is None
            locked = await api.post(f"/api/task/{SLUG}/solution")
            assert locked.status_code == 423, locked.text
            with state.writing() as st:
                o = st["open"][SLUG]
                o.update(attempts=3, active=600, brief={"name": "no", "replicas": 2})
            revealed = await api.post(f"/api/task/{SLUG}/solution")
            assert revealed.status_code == 200, revealed.text
            doc = yaml.safe_load(revealed.json()["reference"])
            assert doc["metadata"]["name"] == "no"
            assert doc["spec"]["replicas"] == 2
            page = await api.get(f"/api/task/{SLUG}")
            assert page.json()["reference"] == revealed.json()["reference"]

    asyncio.run(drive())


def test_a_manifest_pass_returns_its_reference_and_archives_its_revision(
    stubbed_kubeconform,
):
    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            opened = await api.post(f"/api/task/{SLUG}/open")
            assert opened.status_code == 200, opened.text
            o = state.load()["open"][SLUG]
            brief = o["brief"]
            # the answer key itself, rather than a hand-written manifest that would have to
            # be kept schema-valid here as well as in the fixture
            code = manifest.render_solution(meta_for(), brief)
            reply = await api.post(
                f"/api/task/{SLUG}/run",
                json={"code": code, "etag": opened.json()["etag"], "submit": True},
            )
            assert reply.status_code == 200, reply.text
            assert reply.json()["passed"] is True
            assert yaml.safe_load(reply.json()["reference"]) == yaml.safe_load(code)
            saved = state.load()
            assert SLUG not in saved["open"]
            # what judged the pass, which is more than what asked the question: the
            # validator and the schemas decide a manifest verdict too
            assert saved["archive"][SLUG][-1]["revision"] == manifest.fingerprint(
                meta_for()
            )
            assert o["brief_revision"] == manifest.grader_revision(meta_for())
            assert meta_for()["path"].read_text(encoding="utf-8") == ""
            closed = await api.get(f"/api/task/{SLUG}")
            assert closed.status_code == 200, closed.text
            assert closed.json()["status"] == "done"
            # a refresh after the pass still shows the question it asked and its answer
            assert closed.json()["reference"] == reply.json()["reference"]
            assert closed.json()["spec_md"] == o["spec_md"]
            archived = closed.json()["archive"][-1]
            assert archived["kubernetes"] == tools.KUBERNETES_VERSION
            assert "python" not in archived

    asyncio.run(drive())


def test_a_solution_that_will_not_render_does_not_cost_the_learner_the_pass(
    stubbed_kubeconform,
):
    """An answer key that cannot render is the task's bug. Raising here once cost a correct
    submission its pass: `kind.reference` runs inside the same transaction as `record_pass`,
    so the whole thing rolled back and retrying failed forever. `doctor` reports such a task;
    the run still passes, without a reference."""
    solution = settings.tasks_dir / SLUG / "solution.yaml"
    solution.write_text(
        solution.read_text(encoding="utf-8").replace("name: {name}", "name: x-{name}"),
        encoding="utf-8",
    )

    async def drive():
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app), base_url="http://127.0.0.1"
        ) as api:
            opened = (await api.post(f"/api/task/{SLUG}/open")).json()
            b = state.load()["open"][SLUG]["brief"]
            correct = (
                "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n"
                f"  name: {b['name']}\nspec:\n  replicas: {b['replicas']}\n"
            )
            done = await api.post(
                f"/api/task/{SLUG}/run",
                json={"code": correct, "etag": opened["etag"], "submit": True},
            )
            assert done.status_code == 200, done.text
            assert done.json()["passed"], done.text
            assert done.json()["reference"] is None, "no key, but the pass stands"
            assert SLUG not in state.load()["open"], "the sitting closed"

    asyncio.run(drive())


def test_a_grader_upgraded_under_a_live_sitting_still_grades_its_brief(
    stubbed_kubeconform,
):
    """A new grader revision is not a new question: the stored brief is still what the
    learner was shown, so a compatible grader keeps grading it."""
    meta = meta_for()
    o = kinds.of(meta).opening(meta, 1)
    grader = settings.tasks_dir / SLUG / "grade.py"
    grader.write_text(grader.read_text(encoding="utf-8") + "\n# reworded\n", "utf-8")
    assert o["brief_revision"] != manifest.grader_revision(meta_for())
    code = manifest.render_solution(meta_for(), o["brief"])
    (settings.tasks_dir / SLUG / "task.yaml").write_text(code, encoding="utf-8")
    passed, detail = kinds.of(meta_for()).grade(meta_for(), o, code)
    assert passed, detail["headline"]


def test_a_grader_that_cannot_read_the_brief_is_not_the_learner_s_fault(
    stubbed_kubeconform,
):
    """An upgrade whose check() no longer reads a stored brief crashes rather than asserts,
    and that crash is refused as infrastructure instead of charged as a failed attempt."""
    (settings.tasks_dir / SLUG / "task.yaml").write_text(CORRECT, encoding="utf-8")
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        "def brief(r):\n    return {}\n\n\ndef check(doc, b):\n    b['ports']\n",
        encoding="utf-8",
    )
    with pytest.raises(manifest.Rejected, match="KeyError"):
        runner.run_manifest(meta_for(), BRIEF)


def test_a_second_document_can_still_be_saved_while_it_is_being_typed(fixture_root):
    """Saving only asks that it parses, and a multi document stream does. Rejecting it here
    made autosave 400 on every keystroke of a second document, and hid the grader's own
    "expected one document" message behind a PyYAML sentence fragment."""
    two = "apiVersion: v1\nkind: Pod\n---\napiVersion: v1\nkind: Service\n"
    assert kinds.of(meta_for()).validate(two, "") == two
    with pytest.raises(kinds.Invalid):
        kinds.of(meta_for()).validate("a:\n  - [unclosed\n", "")


MULTI = (
    "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: checkout\n"
    "spec:\n  replicas: 3\n---\n"
    "apiVersion: v1\nkind: Pod\nmetadata:\n  name: app\n"
)


def _multi_grader():
    """Swap the fixture task's grader for one that asks for several objects in one file."""
    (settings.tasks_dir / SLUG / "grade.py").write_text(
        "def brief(r):\n"
        "    return {}\n"
        "\n"
        "\n"
        "def check_many(docs, b):\n"
        "    assert [d['kind'] for d in docs] == ['Deployment', 'Pod'], 'kinds'\n"
        "    assert docs[1]['metadata']['name'] == 'app', 'name'\n",
        encoding="utf-8",
    )


def test_a_grader_with_check_many_grades_every_document(stubbed_kubeconform):
    """A task whose answer is several objects in one file is graded on all of them. The
    one-document refusal only belongs to graders still defining `check` alone."""
    _multi_grader()
    passed, headline = _submit(MULTI)
    assert passed, headline


def test_a_check_many_grader_says_which_requirement_missed(stubbed_kubeconform):
    _multi_grader()
    passed, headline = _submit(MULTI.replace("name: app", "name: other"))
    assert not passed and "name" in headline


def test_a_stray_separator_is_not_a_document(stubbed_kubeconform):
    """A trailing `---` makes PyYAML see one more, empty document. kubectl shrugs at it;
    here it is refused by name, because a learner who shipped it to a cluster would get a
    blank object in `kubectl get` and no error at all."""
    _multi_grader()
    passed, headline = _submit(MULTI + "\n---\n")
    assert not passed and "document 3 is not a mapping" in headline
