apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
