apiVersion: v1
kind: Pod
metadata:
  name: {name}
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: {uid}
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: {name}
      image: {image}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}
