apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  clusterIP: None
  selector:
    app: {name}
  ports:
    - port: {port}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {name}
spec:
  serviceName: {name}
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {image}
