apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {name}
spec:
  ingressClassName: {ingressClass}
  tls:
    - hosts:
        - {host}
      secretName: {secret}
  rules:
    - host: {host}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {service}
                port:
                  number: 80
