apiVersion: v1
kind: ConfigMap
metadata:
  name: {name}
data:
  LOG_LEVEL: {value}
---
apiVersion: v1
kind: Pod
metadata:
  name: {pod}
spec:
  containers:
    - name: {pod}
      image: {image}
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {name}
              key: LOG_LEVEL
