apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {root}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {repo}
    targetRevision: main
    path: {root_path}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {infra}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: {repo}
    targetRevision: main
    path: {infra_path}
  destination:
    server: https://kubernetes.default.svc
    namespace: {infra}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {app}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {repo}
    targetRevision: main
    path: {app_path}
  destination:
    server: https://kubernetes.default.svc
    namespace: {app}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
