apiVersion: v1
kind: Service
metadata:
  name: {db}
spec:
  clusterIP: None
  selector:
    app: {db}
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {db}
spec:
  serviceName: {db}
  replicas: 1
  selector:
    matchLabels:
      app: {db}
  template:
    metadata:
      labels:
        app: {db}
    spec:
      containers:
        - name: {db}
          image: {db_image}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {image}
          env:
            - name: DATABASE_HOST
              value: {db}
